### ISSUE TITLE
ESW01-USA and ESW03-USA Device Type Map Issue

### ISSUE THREAD

**Issue by cdnninja** [webdjoe/pyvesync#400]
When a user only has outlets the update all fails with:

```
Error setting up entry [fabiendsophieg@gmail.com](mailto:fabiendsophieg@gmail.com) for vesync
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/vesync/init.py", line 58, in async_setup_entry
await manager.update()
File "/usr/local/lib/python3.13/site-packages/pyvesync/vesync.py", line 454, in update
await self.update_all_devices()
File "/usr/local/lib/python3.13/site-packages/pyvesync/vesync.py", line 462, in update_all_devices
done, _ = await asyncio.wait(update_tasks, return_when=asyncio.ALL_COMPLETED)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/asyncio/tasks.py", line 441, in wait
raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
```

This is the same error that occurs when no devices are set.  This thread speaks to it.  Two people have confirmed they only have outlets. https://github.com/home-assistant/core/issues/153375

**Comment by cdnninja** [comment]
I am guessing that when the device isn't support within outlets it doesn't have a get_details() method so nothing to await.

**Comment by webdjoe** [comment]
I created a branch if you can have them test it: https://github.com/webdjoe/pyvesync/tree/outlet-bug

**Comment by cdnninja** [comment]
User confirmed it worked however the device labels all show was ESW01-USA. I also notice a mention of europe in one of the fields. I am thinking that should be more general.

**Comment by webdjoe** [comment]
This has to do with device type matching. I need some captures on these devices to test, I'm not sure which API calls the ESW03 and ESW01 have.

**Comment by webdjoe** [comment]
Update: ESW01 should be supported in the latest release. I have packet captures for ESW03 and it will be integrated over the next week. For some reason the old devicestatus call is no longer accepted by the API.

**Comment by bcayton** [comment]
@webdjoe any update on the fix for the ESW03 devices? 

Appreciate all the hard work, just trying to decide if I want to replace my ESW03 devices if they are no longer going to be supported.

**Comment by JoshFDXGUS** [comment]
@webdjoe do you anticipate a fix for the ESW03-USA or should we start looking to source replacement devices?

**Comment by cdnninja** [comment]
I know they are working on it.

**Comment by webdjoe** [comment]
Support has been fixed in the latest release if you can please test and confirm. Thank you!

**Comment by JoshFDXGUS** [comment]
If you are referring to 10.3 it did not fix it.  The devices are there but
you cannot toggle the smart plugs.  All attributes are disabled.

**Comment by bcayton** [comment]
@webdjoe its not working for me either, I still can’t see my ESW03 devices. I’m also still getting the email verification on log in which I thought had been previously fixed?

**Comment by cdnninja** [comment]
@webdjoe is referencing it is fixed in the library release.  You can test with the test script.   I will create a pull request to put this into home assistant.

**Comment by webdjoe** [comment]
Please test the library, it needs to be tested at the library level before it can be integrated into HA. https://github.com/webdjoe/pyvesync/tree/master/testing_scripts

**Comment by daliusl54** [comment]
Everything looks ok, power and voltage, but on/off - illegal argument.

2025-11-04 00:25:26.530 WARNING (MainThread) [pyvesync.devices.vesyncoutlet] outlet1 for ESW03-USA API from toggle_switch returned error code: -11000030, message: unknown_error - UNKNOWN Unknown error - illegal argument
2025-11-04 00:25:26.635 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547280147040] Error during service call to switch.turn_off: Unknown error - illegal argument
2025-11-04 00:25:27.315 WARNING (MainThread) [pyvesync.devices.vesyncoutlet] outlet1 for ESW03-USA API from toggle_switch returned error code: -11000030, message: unknown_error - UNKNOWN Unknown error - illegal argument
2025-11-04 00:25:27.358 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547280147040] Error during service call to switch.turn_on: Unknown error - illegal argument
2025-11-04 00:25:27.860 WARNING (MainThread) [pyvesync.devices.vesyncoutlet] outlet1 for ESW03-USA API from toggle_switch returned error code: -11000030, message: unknown_error - UNKNOWN Unknown error - illegal argument
2025-11-04 00:25:27.896 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547280147040] Error during service call to switch.turn_off: Unknown error - illegal argument
2025-11-04 00:25:28.494 WARNING (MainThread) [pyvesync.devices.vesyncoutlet] outlet1 for ESW03-USA API from toggle_switch returned error code: -11000030, message: unknown_error - UNKNOWN Unknown error - illegal argument
2025-11-04 00:25:28.507 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547280147040] Error during service call to switch.turn_on: Unknown error - illegal argument

**Comment by webdjoe** [comment]
Thank you for the update, this will be fixed in the next release

**Comment by BrandonEgan** [comment]
Hi, copying my comment from the thread in home-assistant. Would your fix also address my issue, or am I possibly having a different issue?:

> Hi I am also having an issue with some of my Vesync plugs. I have (3) ESW01-USA plugs and (7) ESW01-USA-R6P plugs and the HA Vesync integration is only pulling in the 3 ESW01-USA plugs. The ESW01-USA-R6P plugs no longer pull into HA. I can't say when exactly it started but I think it was after updating to 2025.10.x
> 
> Interestingly, my debug logs show as ESW03-USA but the affected units are ESW01-USA-R6P. But the number of "not found" (7) vs "already exists" (3) devices lines up

> �[36m2025-10-25 00:46:27.342 DEBUG (MainThread) [pyvesync.auth] Login successful for user: EMAIL�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device type ESW03-USA not found in device map�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device already exists�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device already exists�[0m
�[36m2025-10-25 00:46:27.432 DEBUG (MainThread) [pyvesync.device_container] Device already exists�[0m

**Comment by daliusl54** [comment]
This was already addressed in current pyvesync.

**Comment by BrandonEgan** [comment]
> This was already addressed in current pyvesync.

Thanks, I wasn't sure if it was the same issue or not since my model number was different. I just updated to HA 2025.11.0 and I see the plugs again! But unfortunately I am getting the same illegal argument error you are. I will wait for the fix in the next release per webdjoe's comment

Thanks all! 😄

**Comment by daliusl54** [comment]
> > This was already addressed in current pyvesync.
> 
> Thanks, I wasn't sure if it was the same issue or not since my model number was different. I just updated to HA 2025.11.0 and I see the plugs again! But unfortunately I am getting the same illegal argument error you are. I will wait for the fix in the next release per webdjoe's comment
> 
> Thanks all! 😄

I didn't finish reading, I suspect it's only about ESW03-USA

**Comment by daliusl54** [comment]
looks ok now

2025-11-09 11:14:55.381 DEBUG (MainThread) [pyvesync.devices.vesyncoutlet] Dajaus lava lempa for ESW03-USA API from toggle_switch returned code: 0, message: success - Success - request success
2025-11-09 11:14:56.298 DEBUG (MainThread) [pyvesync.vesync] ==================API CALL==================
Caller: VeSyncOutlet10A.call_bypassv1_api [devices.vesyncoutlet]
API CALL to endpoint: /cloud/v1/deviceManaged/deviceStatus
Host: smartapi.vesync.com
Full URL: https://smartapi.vesync.com/cloud/v1/deviceManaged/deviceStatus
Response Status: 200
Method: POST
---------------Request-----------------
Request Headers: 
 {
  "Content-Type": "application/json; charset=UTF-8",
  "User-Agent": "okhttp/3.12.1"
}
Request Body: 
 {
  "acceptLanguage": "en",
  "accountID": "##_REDACTED_##",
  "appVersion": "5.6.60",
  "cid": "##_REDACTED_##",
  "configModule": "10AOutletUS",
  "debugMode": false,
  "method": "deviceStatus",
  "phoneBrand": "pyvesync",
  "phoneOS": "Android",
  "traceId": "1762704896",
  "timeZone": "America/New_York",
  "token": "##_REDACTED_##",
  "userCountryCode": "US",
  "uuid": "##_REDACTED_##",
  "deviceId": "0LotOWKnc8r4to99p4g_xE5rsgzuoL3z",
  "configModel": "10AOutletUS",
  "status": "off"
}
---------------Response-----------------
Response Headers: 
 {
  "Date": "Sun, 09 Nov 2025 16:14:56 GMT",
  "Content-Type": "application/json;charset=UTF-8",
  "Transfer-Encoding": "chunked",
  "Connection": "keep-alive",
  "Content-Encoding": "gzip"
}
Response Body: 
 {
  "traceId": "1762704896",
  "code": 0,
  "msg": "request success",
  "module": null,
  "stacktrace": null,
  "result": {}
}
2025-11-09 11:14:56.299 DEBUG (MainThread) [pyvesync.devices.vesyncoutlet] Dajaus lava lempa for ESW03-USA API from toggle_switch returned code: 0, message: success - Success - request success

**Comment by webdjoe** [comment]
Great, thank you for confirming!
